# Generated by Django 4.0.4 on 2022-05-21 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='alias',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9-_]+$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9-_]+$')]),
        ),
    ]
